### PR TITLE
docs updates

### PR DESCRIPTION
**Pull request by paulirish**
bring it up to date with your promise use.

### CODE REVIEW

**Comment by olalonde** [comment]
Wait I'm confused. Does this actually work? I was under the impression I hadn't implemented promises. Unless the oauth module returns promises?

**Comment by paulirish** [comment]
been a while so i forget…
but the library is definitely working like that now.

**Comment by crrobinson14** [comment]
Was this sent in meant for a different repo? This definitely does not work for me, and the lib/yelp.js code is absolutely still using callbacks.

**Comment by olalonde** [comment]
Yes, I'm also confused. I supposed it might work with `var yelp = require("bluebird").promisifyAll(require('yelp'));` but I'm not sure.

**Comment by paulirish** [comment]
Indeed.

I was using https://github.com/Woorank/node-yelp  :)

sorry about that!

**Pull request closed without merging**
